
package com.geored.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UsuarioServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/UsuarioServiceImpl?wsdl")
public class UsuarioServiceImplService
    extends Service
{

    private final static URL USUARIOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.geored.ws.UsuarioServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.geored.ws.UsuarioServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/GeoRed-Business-EJB/UsuarioServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/GeoRed-Business-EJB/UsuarioServiceImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USUARIOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public UsuarioServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioServiceImplService() {
        super(USUARIOSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://negocio.geored.com/", "UsuarioServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns UsuarioServiceImpl
     */
    @WebEndpoint(name = "UsuarioServiceImplPort")
    public UsuarioServiceImpl getUsuarioServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "UsuarioServiceImplPort"), UsuarioServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioServiceImpl
     */
    @WebEndpoint(name = "UsuarioServiceImplPort")
    public UsuarioServiceImpl getUsuarioServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "UsuarioServiceImplPort"), UsuarioServiceImpl.class, features);
    }

}
