
package com.geored.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdminServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/AdminServiceImpl?wsdl")
public class AdminServiceImplService
    extends Service
{

    private final static URL ADMINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.geored.ws.AdminServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.geored.ws.AdminServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/GeoRed-Business-EJB/AdminServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/GeoRed-Business-EJB/AdminServiceImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADMINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public AdminServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminServiceImplService() {
        super(ADMINSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://negocio.geored.com/", "AdminServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns AdminServiceImpl
     */
    @WebEndpoint(name = "AdminServiceImplPort")
    public AdminServiceImpl getAdminServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "AdminServiceImplPort"), AdminServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminServiceImpl
     */
    @WebEndpoint(name = "AdminServiceImplPort")
    public AdminServiceImpl getAdminServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "AdminServiceImplPort"), AdminServiceImpl.class, features);
    }

}
