
package com.geored.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdminServiceImpl", targetNamespace = "http://negocio.geored.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdminServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizar", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.Actualizar")
    @ResponseWrapper(localName = "actualizarResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.ActualizarResponse")
    public void actualizar(
        @WebParam(name = "arg0", targetNamespace = "")
        AdministradorDTO arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.geored.ws.AdministradorDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerListado", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.ObtenerListado")
    @ResponseWrapper(localName = "obtenerListadoResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.ObtenerListadoResponse")
    public List<AdministradorDTO> obtenerListado();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminar", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.Eliminar")
    @ResponseWrapper(localName = "eliminarResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.EliminarResponse")
    public void eliminar(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertar", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.Insertar")
    @ResponseWrapper(localName = "insertarResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.InsertarResponse")
    public Long insertar(
        @WebParam(name = "arg0", targetNamespace = "")
        AdministradorDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.geored.ws.AdministradorDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtener", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.Obtener")
    @ResponseWrapper(localName = "obtenerResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.ws.ObtenerResponse")
    public AdministradorDTO obtener(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
