
package com.geored.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmpresaServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/EmpresaServiceImpl?wsdl")
public class EmpresaServiceImplService
    extends Service
{

    private final static URL EMPRESASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.geored.ws.EmpresaServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.geored.ws.EmpresaServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/GeoRed-Business-EJB/EmpresaServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/GeoRed-Business-EJB/EmpresaServiceImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPRESASERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public EmpresaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpresaServiceImplService() {
        super(EMPRESASERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://negocio.geored.com/", "EmpresaServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns EmpresaServiceImpl
     */
    @WebEndpoint(name = "EmpresaServiceImplPort")
    public EmpresaServiceImpl getEmpresaServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "EmpresaServiceImplPort"), EmpresaServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpresaServiceImpl
     */
    @WebEndpoint(name = "EmpresaServiceImplPort")
    public EmpresaServiceImpl getEmpresaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "EmpresaServiceImplPort"), EmpresaServiceImpl.class, features);
    }

}
