
package com.geored.backoffice.wsclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NegocioException", targetNamespace = "http://negocio.geored.com/")
public class NegocioException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NegocioException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NegocioException_Exception(String message, NegocioException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NegocioException_Exception(String message, NegocioException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.geored.backoffice.wsclient.NegocioException
     */
    public NegocioException getFaultInfo() {
        return faultInfo;
    }

}
