
package com.geored.backoffice.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuarioServiceImpl", targetNamespace = "http://negocio.geored.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioServiceImpl {


    /**
     * 
     * @param arg0
     * @throws NegocioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "actualizar", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.Actualizar")
    @ResponseWrapper(localName = "actualizarResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.ActualizarResponse")
    public void actualizar(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioDTO arg0)
        throws NegocioException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.geored.backoffice.wsclient.UsuarioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerListado", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.ObtenerListado")
    @ResponseWrapper(localName = "obtenerListadoResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.ObtenerListadoResponse")
    public List<UsuarioDTO> obtenerListado();

    /**
     * 
     * @param arg0
     * @throws NegocioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "eliminar", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.Eliminar")
    @ResponseWrapper(localName = "eliminarResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.EliminarResponse")
    public void eliminar(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws NegocioException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     * @throws NegocioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertar", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.Insertar")
    @ResponseWrapper(localName = "insertarResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.InsertarResponse")
    public Long insertar(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioDTO arg0)
        throws NegocioException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.geored.backoffice.wsclient.UsuarioDTO
     * @throws NegocioException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtener", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.Obtener")
    @ResponseWrapper(localName = "obtenerResponse", targetNamespace = "http://negocio.geored.com/", className = "com.geored.backoffice.wsclient.ObtenerResponse")
    public UsuarioDTO obtener(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws NegocioException_Exception
    ;

}
