
package com.geored.backoffice.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpresaServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/EmpresaServiceImpl?wsdl")
public class EmpresaServiceImplService
    extends Service
{

    private final static URL EMPRESASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPRESASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EMPRESASERVICEIMPLSERVICE_QNAME = new QName("http://negocio.geored.com/", "EmpresaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GeoRed-Business-EJB/EmpresaServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPRESASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EMPRESASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EmpresaServiceImplService() {
        super(__getWsdlLocation(), EMPRESASERVICEIMPLSERVICE_QNAME);
    }

    public EmpresaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPRESASERVICEIMPLSERVICE_QNAME, features);
    }

    public EmpresaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EMPRESASERVICEIMPLSERVICE_QNAME);
    }

    public EmpresaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPRESASERVICEIMPLSERVICE_QNAME, features);
    }

    public EmpresaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpresaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpresaServiceImpl
     */
    @WebEndpoint(name = "EmpresaServiceImplPort")
    public EmpresaServiceImpl getEmpresaServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "EmpresaServiceImplPort"), EmpresaServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpresaServiceImpl
     */
    @WebEndpoint(name = "EmpresaServiceImplPort")
    public EmpresaServiceImpl getEmpresaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "EmpresaServiceImplPort"), EmpresaServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPRESASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EMPRESASERVICEIMPLSERVICE_EXCEPTION;
        }
        return EMPRESASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
