
package com.geored.backoffice.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SitioServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/SitioServiceImpl?wsdl")
public class SitioServiceImplService
    extends Service
{

    private final static URL SITIOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SITIOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SITIOSERVICEIMPLSERVICE_QNAME = new QName("http://negocio.geored.com/", "SitioServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GeoRed-Business-EJB/SitioServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SITIOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SITIOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SitioServiceImplService() {
        super(__getWsdlLocation(), SITIOSERVICEIMPLSERVICE_QNAME);
    }

    public SitioServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SITIOSERVICEIMPLSERVICE_QNAME, features);
    }

    public SitioServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SITIOSERVICEIMPLSERVICE_QNAME);
    }

    public SitioServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SITIOSERVICEIMPLSERVICE_QNAME, features);
    }

    public SitioServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SitioServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SitioServiceImpl
     */
    @WebEndpoint(name = "SitioServiceImplPort")
    public SitioServiceImpl getSitioServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "SitioServiceImplPort"), SitioServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SitioServiceImpl
     */
    @WebEndpoint(name = "SitioServiceImplPort")
    public SitioServiceImpl getSitioServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "SitioServiceImplPort"), SitioServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SITIOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SITIOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SITIOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
