
package com.geored.backoffice.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventoServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/EventoServiceImpl?wsdl")
public class EventoServiceImplService
    extends Service
{

    private final static URL EVENTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVENTOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EVENTOSERVICEIMPLSERVICE_QNAME = new QName("http://negocio.geored.com/", "EventoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GeoRed-Business-EJB/EventoServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EVENTOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EventoServiceImplService() {
        super(__getWsdlLocation(), EVENTOSERVICEIMPLSERVICE_QNAME);
    }

    public EventoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public EventoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EVENTOSERVICEIMPLSERVICE_QNAME);
    }

    public EventoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTOSERVICEIMPLSERVICE_QNAME, features);
    }

    public EventoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EventoServiceImpl
     */
    @WebEndpoint(name = "EventoServiceImplPort")
    public EventoServiceImpl getEventoServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "EventoServiceImplPort"), EventoServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventoServiceImpl
     */
    @WebEndpoint(name = "EventoServiceImplPort")
    public EventoServiceImpl getEventoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "EventoServiceImplPort"), EventoServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EVENTOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return EVENTOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
