
package com.geored.backoffice.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OfertaServiceImplService", targetNamespace = "http://negocio.geored.com/", wsdlLocation = "http://localhost:8080/GeoRed-Business-EJB/OfertaServiceImpl?wsdl")
public class OfertaServiceImplService
    extends Service
{

    private final static URL OFERTASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OFERTASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName OFERTASERVICEIMPLSERVICE_QNAME = new QName("http://negocio.geored.com/", "OfertaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GeoRed-Business-EJB/OfertaServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFERTASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        OFERTASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OfertaServiceImplService() {
        super(__getWsdlLocation(), OFERTASERVICEIMPLSERVICE_QNAME);
    }

    public OfertaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFERTASERVICEIMPLSERVICE_QNAME, features);
    }

    public OfertaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, OFERTASERVICEIMPLSERVICE_QNAME);
    }

    public OfertaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFERTASERVICEIMPLSERVICE_QNAME, features);
    }

    public OfertaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfertaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfertaServiceImpl
     */
    @WebEndpoint(name = "OfertaServiceImplPort")
    public OfertaServiceImpl getOfertaServiceImplPort() {
        return super.getPort(new QName("http://negocio.geored.com/", "OfertaServiceImplPort"), OfertaServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfertaServiceImpl
     */
    @WebEndpoint(name = "OfertaServiceImplPort")
    public OfertaServiceImpl getOfertaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.geored.com/", "OfertaServiceImplPort"), OfertaServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFERTASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw OFERTASERVICEIMPLSERVICE_EXCEPTION;
        }
        return OFERTASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
